CUDA_VISIBLE_DEVICES="0" python train.py \
        --train_dir="../model/video_chain_moe16_verydeep_combine/" \
        --frame_features=False \
        --feature_names="mean_rgb,mean_audio" \
        --feature_sizes="1024,128" \
        --model=DeepCombineChainModel \
        --label_loss=MultiTaskCrossEntropyLoss \
        --train_data_pattern="/Youtube-8M/data/video/train/train*" \
        --batch_size=512 \
        --multitask=True \
        --support_type="label,label,label,label,label,label,label,label" \
        --support_loss_percent=0.025 \
        --moe_num_mixtures=2 \
        --keep_checkpoint_every_n_hours=0.25 \
        --num_readers=4 \
        --deep_chain_layers=8 \
        --deep_chain_relu_cells=128 \
        --base_learning_rate=0.004

