
CUDA_VISIBLE_DEVICES=0 python train.py \
    --train_dir="../x27_model/lstm_positional_attention8max" \
    --train_data_pattern="/Youtube-8M/data/frame/train/train*" \
    --frame_features=True \
    --feature_names="rgb,audio" \
    --feature_sizes="1024,128" \
    --reweight=True \
    --sample_vocab_file="resources/train.video_id.vocab" \
    --sample_freq_file="resources/train.video_id.freq" \
    --model=LstmPositionalAttentionMaxPoolingModel \
    --moe_num_mixtures=8 \
    --lstm_attentions=8 \
    --positional_embedding_size=32 \
    --rnn_swap_memory=True \
    --base_learning_rate=0.001 \
    --num_readers=4 \
    --num_epochs=6 \
    --batch_size=128 \
    --keep_checkpoint_every_n_hour=0.5
