CUDA_VISIBLE_DEVICES=0 python train.py \
		--train_data_pattern='/Youtube-8M/data/video/train/*.tfrecord' \
		--train_dir='../model/video_level_moemix4_relabel_model' \
		--model='MoeMix4Model' \
		--feature_names="mean_rgb, mean_audio" \
		--feature_sizes="1024, 128" \
		--moe_num_mixtures=4 \
		--moe_layers=3 \
		--class_size=100 \
		--loss_function="loss_relabel"